package utils

import (
	"mirage-backend/docs" // docs is generated by Swag CLI, you have to import it.
)

func SetupDocs() {
	docs.SwaggerInfo.Title = "Mirage API"
	docs.SwaggerInfo.Description = "This is the backend REST API for Mirage."
	docs.SwaggerInfo.Version = "0.1.0"
	docs.SwaggerInfo.Host = "localhost:8080"
	docs.SwaggerInfo.BasePath = "/api/v1"
	docs.SwaggerInfo.Schemes = []string{"http"}
}
